version: '3.8'

services:
    postgres:
        build:
            context: ./postgres
        container_name: todos_postgres
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - db_network
        ports:
            - "${POSTGRES_PORT}:5432"

    adminer:
        build:
            context: ./adminer
        container_name: todos_adminer
        restart: always
        environment:
            - ADMINER_DEFAULT_SERVER=postgres
        networks:
            - db_network
        ports:
            - "${ADMINER_PORT}:8080"
        depends_on:
            - postgres

networks:
    db_network:
        driver: bridge

volumes:
    postgres_data:
